Creating product landing page
MasomRezaie/product-landing-page pull request #1
Opened 2024-05-29 11:31 UTC by MasomRezaie

This a project is built by html and CSS.
I configured linters.
I tested in freecodecamp.org.

2024-05-30 17:55 UTC, ahzamir requested changes
### Hi @MasomRezaie 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Although your code is passing all the checks on the freecodecamp website, but you need to work on your project in order to get the final approval.
  - Check the inline comments below for more details.
  
# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
✔️ Simple Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed and completed the Product Landing Page and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
❌Your code is clean
❌Your project has a professional README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-30 17:55 UTC, ahzamir commented on index.html
> +  <iframe src="./4698fa6d9226e920c480e4dcf544e53356043559-144p.mp4" frameborder="0" id="video"></iframe>
- Your section does not have a closing tag.

2024-05-30 17:55 UTC, ahzamir commented on README.md
- Here you guided the user on how to create a product landing page, instead, you have to guide the user on what your project is about, how to use it, how you made it, and all the info about it.

2024-05-30 17:55 UTC, ahzamir commented on styles.css
- **[OPTIONAL]** - Although your code passes the freecodecamp tests, I suggest adding more content to your webpage and some design to make it look more awesome to share.

2024-06-01 05:04 UTC, MasomRezaie commented
@ahzamir Hi sir, hope you are doing well. I applied your feedback. Please re-review.

2024-06-01 09:46 UTC, ahzamir approved these changes
### Hi @MasomRezaie 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![GreatJobThumbsUpGIF](https://github.com/ZuhRa-HashiMi/survey-form/assets/96838030/cc459d3f-5796-43f0-aba7-4ed0c35fa276)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Product Landing Page project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your project has a professional README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-04 18:27 UTC, ahzamir commented
@MasomRezaie 

- Why you did not merge your branch after getting the approval?

2024-06-05 10:52 UTC, merged